# User
title: Lorem Ipsum
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
phone: 012 34 56 78
address:
 - Lorem Ipsum 47
 - 123 45 Dolor
 - Sit amet
facebook:
twitter:
instagram:
linkedin:

# Admin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
permalink: pretty
paginate: 3
google_analytics:

# Build settings
markdown: kramdown
exclude:
 - unicorn.rb
 - README.md
 - Procfile
 - Gemfile
 - Gemfile.lock
 - config.ru
 - vendor
 - app.json
